Literature Review (deep_research):
    server_model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 1
    device: gpu
    type: deep_research
    mps: 33

Generating Meeting Notes (live_captions):
    num_requests: 1
    device: gpu
    client_command_file: /home/cc/datasets/whisper-earnings21/5-min-chunks/4320211_chunk_002.wav
    mps: 33
    type: live_captions  

Brainstorm (chatbot):
    server_model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 10
    device: gpu
    type: chatbot
    mps: 33

workflows:
    literature_review:
        uses: Literature Review (deep_research)
        background: true
    
    meeting_notes:
        uses: Generating Meeting Notes (live_captions) 

    brainstorm:
        uses: Brainstorm (chatbot)
        depend_on: ["meeting_notes", "literature_review"]
