Brainstorm (chatbot):
    server_model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 10
    device: gpu
    type: chatbot
    mps: 100

Analysis (deep_research):
    server_model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 1
    device: gpu
    type: deep_research
    mps: 100

Preparing Outline (chatbot):
    server_model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 20
    device: gpu
    type: chatbot
    mps: 100

Creating Cover Art (imagegen):
    server_model: /mnt/tmpfs/models/stable-diffusion-3.5-medium-turbo
    num_requests: 10
    device: gpu
    type: imagegen
    mps: 100

Generating Captions (live_captions):
    num_requests: 1
    device: gpu
    client_command_file: /home/cc/datasets/whisper-earnings21/5-min-chunks/4320211_chunk_002.wav
    mps: 100
    type: live_captions  

workflows:
    analysis:
        uses: Analysis (deep_research)
        background: true
    
    brainstorm: 
        uses: Brainstorm (chatbot)

    outline:
        uses: Preparing Outline (chatbot)
        depend_on: ["brainstorm", "analysis"]

    cover_art:
        uses: Creating Cover Art (imagegen)
        depend_on: ["outline"]

    generate_captions:
        uses: Generating Captions (live_captions)
        depend_on: ["outline"]
